version: '3.4'

services:
    server:
      build:
        context: ./
        dockerfile: ./server/Dockerfile
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./server:/server
      ports:
        - "8000:8000"
      depends_on:
        - db
        - celery
        - redis
      environment:
          DEBUG: 'True'
          DATABASE_URL: 'postgres://postgres:@db:5432/postgres'
          REDIS_URL: 'redis://redis:6379/0'
          BROKER_URL: 'amqp://user:password@rabbitmq:5672/my_vhost'

    db:
        image: postgres:11.2
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
        ports:
          - 5432:5432

    rabbitmq:
        image: rabbitmq:3.7.5
        environment:
            RABBITMQ_DEFAULT_USER: 'user'
            RABBITMQ_DEFAULT_PASS: 'password'
            RABBITMQ_DEFAULT_VHOST: 'my_vhost'

    celery:
        build:
            context: ./
            dockerfile: ./server/Dockerfile
        command: celery -A config worker -B -l info -Q default,celery -s /var/run/celerybeat-schedule
        volumes:
            - ./server:/server
        depends_on:
            - db
            - rabbitmq
        environment:
            DEBUG: 'True'
            DATABASE_URL: 'postgres://postgres:@db:5432/postgres'
            BROKER_URL: 'amqp://user:password@rabbitmq:5672/my_vhost'
            REDIS_URL: 'redis://redis:6379/0'

    redis:
      image: redis:5.0.5-alpine
