DEFAULT_CURRENCY = 'EUR'
CURRENCIES = ('EUR', 'USD', 'CZK', 'PLN')
MAX_CONVERT_AMOUNT = 1000000000
EU_CENTRAL_BANK_URL = 'https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml'
DECIMAL_PLACES = 4
MAX_RELATION_TO_CURRENCY_DIGITS = 12
UPDATE_TIME_LIMIT = 60 * 60
RATE_TIMELIFE = 60 * 60 * 24
